配置名称:
  世界书本地文件夹: 世界书各条目拆开为单个条目的文件后, 那些文件所在的文件夹. 如 D:\SillyTavern\世界书, 其中 \ 也可以换成 /
  世界书酒馆文件: 世界书 json 文件的绝对路径. 如 D:\SillyTavern\SillyTavern\data\default-user\worlds\舰娘3.json, 其中 \ 也可以换成 /
  玩家名: 填入你 <user> 的名字, 则同步时会自动将名字替换成 <user>

舰娘3:
  世界书本地文件夹: D:\SillyTavern\世界书
  世界书酒馆文件: D:\SillyTavern\SillyTavern\data\default-user\worlds\舰娘3.json
  玩家名: 阿伟

配置名称（带发布功能）:
  世界书本地文件夹: 世界书各条目拆开为单个条目的文件后, 那些文件所在的文件夹. 如 D:/三个女孩各有秘密/世界书, 其中 / 也可以换成 \
  世界书酒馆文件: 世界书 json 文件的绝对路径. 如 D:/SillyTavern/SillyTavern/data/default-user/worlds/-三个女孩各有秘密.json, 其中 / 也可以换成 \
  世界书名称: 这个设置主要是针对 VPS 提供, 让云酒馆也能使用 watch 功能, 如果填写了"世界书酒馆文件"则不必填写这个. 如 -三个女孩各有秘密
  玩家名: 填入你 <user> 的名字, 则同步时会自动将名字替换成 <user>
  发布目标文件夹: 要打包到的文件夹路径, 如 D:/发布文件夹
  角色卡: 角色卡路径, 如 D:/SillyTavern/data/default-user/characters/三个女孩各有秘密.png
  源文件文件夹: 要同时发布的原始文件路径, 如 D:/三个女孩各有秘密, 其中有世界书、第一条消息等文件夹, 则将会一并发布

三个女孩各有秘密:
  世界书本地文件夹: D:/三个女孩各有秘密/世界书
  世界书酒馆文件: D:/SillyTavern/SillyTavern/data/default-user/worlds/-三个女孩各有秘密.json
  玩家名: 青空莉
  发布目标文件夹: D:/发布文件夹
  角色卡: D:/SillyTavern/data/default-user/characters/三个女孩各有秘密.png
  源文件文件夹: D:/三个女孩各有秘密
